[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/CCS-ZCU/pribehy-dat/blob/master/scripts/nlp.ipynb)

Tento soubor je součástí sestavy elektronických studijních opor [Příběhy dat: Výpočetní přístupy ke studiu kultury a společnosti](https://github.com/CCS-ZCU/pribehy-dat/tree/master).

# NLP: Zpracování přirozeného jazyka

**autor**: *Vojtěch Kaše* (kase@ff.zcu.cz)

[![](https://ccs.zcu.cz/wp-content/uploads/2021/10/cropped-ccs-logo_black_space_240x240.png)](https://ccs.zcu.cz)

## Úvod a cíle kapitoly

Cílem tohoto cvičení je provést základní kvantitativní textovou analýzu vybraného dokumentu z **Archivu Jana Patočky**. Bohužel webová verze archivu, s online přístupnými Patočkovými texty, je v tuto chvíli (tj. jaro 2026) nedostupná (původní odkaz [zde](https://archiv.janpatocka.cz/items/browse?tags=fulltext)). Proto v tomto roce využijeme dokumenty zálohované z minulých let.

## Cvičení

V tomto cvičení je konfigurace potřebných knihoven o něco komplexnější.

In [1]:
%%capture
!pip install stanza
import stanza
stanza.download("cs")
czech_pipeline = stanza.Pipeline("cs")
import requests
from urllib.request import urlopen # pro práci w webovými adresami
from bs4 import BeautifulSoup # pro práci s webovými stránkami ve formátu html
import pandas as pd # pro práci s tabulkami ve formátu dataframe
import nltk # modul pro práci s textovými daty
from sklearn.feature_extraction.text import CountVectorizer
nltk.download('punkt')
import matplotlib.pyplot as plt # modul pro vytváření grafů
import numpy as np # modul pro pokročilejší matematické operace
import re
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics.pairwise import cosine_similarity

Nyní si načteme tabulku textů připravenou z minulých let.

In [4]:
patocka_all_df = pd.read_parquet("https://raw.githubusercontent.com/CCS-ZCU/pribehy-dat/refs/heads/master/data/patocka_all_raw_df.parquet")
patocka_all_df

,url,title,date,rawtext
ajp_id,,,,
98,https://archiv.janpatocka.cz/items/show/98,"Recenze na: J. Kratochvil, Meditace věků. Ději...",1932,Josef Kratochvil: Meditace věků. Dějinný vývoj...
335,https://archiv.janpatocka.cz/items/show/335,"Recenze na: H. Gouhier, La jeunesse d’Auguste ...",1936,None
66,https://archiv.janpatocka.cz/items/show/66,"Recenze na: J. Benda, La fin de l’éternel",1929,"Julien Benda, La fin de 1’eternel, Paris, Gall..."
30,https://archiv.janpatocka.cz/items/show/30,Gorgias\n,None,﻿Ještě ve stručnosti zopakuji hlavní body té K...
95,https://archiv.janpatocka.cz/items/show/95,"Recenze na: G. Ipsen, Sprachphilosophie der Ge...",1932,"Philosophische Forschungsberichte, Junker und ..."
...,...,...,...,...
391,https://archiv.janpatocka.cz/items/show/391,"Recenze na: L. Rieger, Idea filosofie",1938,None
364,https://archiv.janpatocka.cz/items/show/364,"Recenze na: L. Robin, Platon",1937,None
282,https://archiv.janpatocka.cz/items/show/282,"Recenze na: L. von Wiese, System der allgemein...",1933,Leopold von Wiese: System der allgemeinen Sozi...
2661,https://archiv.janpatocka.cz/items/show/2661,Co je Evropa – šest zlomků,None,[Bytí: kosmos věcí...]1 Sein: Kosmos der Dinge...
8,https://archiv.janpatocka.cz/items/show/8,Aristotelés I.\n,Magnetofonový kotouč\n,﻿Posledně jsme k Parmenidově nauce o SÉMATA TÚ...

Naším prvním úkolem bude si z této tabulky vybrat jeden konkrétní dokument dle našeho vkusu. Tabulku můžeme různým způsobem procházet, např. si z ní zobrazit náhodný vzorek 10 dokumentů pomocí `patocka_all_df.sample(10)`.

Když si konkrétní dokument vybereme, poznamenáme si jeho ID, které vidíme ve sloupci úplně vlevo ("ajp_id").

Toto ID je tím jediným, čím se v archivu odlišují URL adresy jednotlivých dokumentů, ale to jsou nyní bohužel mimo provoz. Přesto si můžeme adresu zobrazit.

**SAMOSTATNÝ ÚKOL**: v následující buňce vyplňte ajp_id vámi zvoleného dokumentu.

In [ ]:
doc_id =      # před symbolem hashtagu doplňte id dokumentu z tabulky patocka_all_df
url = "https://archiv.janpatocka.cz/items/show/" + str(doc_id)
url

In [ ]:
# Tato buňka slouží ke kontrole průchodu tímto cvičením.
# Pokud toto cvičení plníte v rámci svých studijních povinností na ZČU, buňku spusťte a držte se instrukcí.
exec(requests.get("https://sciencedata.dk/shared/856b0a7402aa7c7258186a8bdb329bd3?download").text)
kontrola_pruchodu(ntb="nlp", arg1=url)

Nyní si vybereme z tabulky data odpovídající námi zvolenému dokumentu.

In [ ]:
doc_df = patocka_all_df.loc[doc_id]
doc_df

In [ ]:
# můžeme odtud vyvolat název dokumentu:
doc_df["title"]

In [ ]:
# ...ale zejména jeho text
text_dokumentu = doc_df["rawtext"]
# ten si nyní vyobrazíme:
print(text_dokumentu)

In [ ]:
# dokument jako list slov získáme pomocí funkce "split()"
# uložíme si ho takto do nové proměnné "string_list"
string_list = text_dokumentu.split()
# prvních 20 prvků tohoto listu si nyní vypíšeme:
string_list[:20]

In [ ]:
### pomocí funkce "len()" spočítáme délku tohoto listu slov:
len(string_list)

### Lematizace a postagging

S textem článku, tak jak se nyní nachází v proměnné "text_clanku", bychom se ale při kvantitativní textové analýze stále příliš daleko nedostali. Čeština je totiž morfologicky velice bohatý jazyk. Chceme-li např. spočítat kolikrát se v textu objevuje sloveso "mít", s textem v aktuální podobě se příliš daleko nedstaneme. Zde potřebujeme na naše textová data aplikovat dvě další procedury:


1.   lemmatizace, tj. převedení slov z textu do jejich základních tvarů (slovesa do infinitivu, podstatná jména do 1.pádu singuláru apod.)
2.   POS-tagging ("part-of-speech tags"),  tj. určení slovních druhů a mluvnických kategorií

Aplikace těchto procedur nám umožní získat data z hlediska kvantitativní textové analýzy výrazně zajímavější.

V případě češtiny se můžeme v tomto případě opřít o model pro jazykový model pro zpracování češtiny vyvinutý pro knihovnu [stanza](https://stanfordnlp.github.io/stanza/), konkrétně [stanza-cs](https://huggingface.co/stanfordnlp/stanza-cs).

In [ ]:
sent = "Česká republika je velmi sebevědomý stát, který dokáže stát na vlastních nohách."
doc = czech_pipeline(sent)
doc

In [ ]:
# jiný příklad ukáže limity tohoto modelu:
sent = "Ptáci seděli na smrku a jedli."
doc = czech_pipeline(sent)
[t.lemma for t in doc.sentences[0].words]

In [ ]:
# nyní aplikujeme na celý Patočkův dokument.
# vytvoříme morfoligicky zpracovanou verzi našeho textu a konvenčně si ji uložíme do proměnně `doc`.
doc = czech_pipeline(text_dokumentu)

Tímto jsme vytvořili morfoligicky zpracovanou verzi našeho textu a konvenčně si ji uložili do proměnně `doc`. Tento objekt nyní neobsahuje pouze syrový text, ale také text rozdělený do vět, každou větu na jednotlivá slova a každému slovo je automaticky přiřazeno jeho *lemma*, morfologické určení a některé další atributy. Na tuto datovou strukturou se můžeme nyní pracovat např. následujícím způsobem:

In [ ]:
data = []
for i, sentence in enumerate(doc.sentences):
  for token in sentence.words:
    data.append({
      'sent_n' : i,
      'text': token.text,
      'lemma': token.lemma,
      'upos': token.upos,
      'xpos': token.xpos
    })
data_df = pd.DataFrame(data)
data_df[30:40]

Obdobně můžeme vybrat z vět pouze lemmata slov vybraných slovních druhů:

In [ ]:
lemmatized_sentences = []
for sent in doc.sentences:
  sentence_lemmata = []
  for token in sent.words:
    if token.upos in ["PROPN", "NOUN", "VERB", "ADJ"]:
      sentence_lemmata.append(token.lemma)
  lemmatized_sentences.append(sentence_lemmata)

In [ ]:
lemmatized_sentences[:3]

V této podobě může být již vcelku zajímavé podívat se na frekvence výskytů slov, resp. jejich lematizovaných tvarů. K tomu použijeme funkce z modulu "nltk".

In [ ]:
# nejprve si z naší filtrované tabulky vyxtrahujeme lemmata samotná
lemmata = [l for s in lemmatized_sentences for l in s]
# pro každý jednotlivý výraz necháme spočítat jeho počet výskytů
lemmata_freq = nltk.FreqDist(lemmata)
# vybereme např. 10 nejfrekventovanějších slov (rozumějme lemmatizovaných substantiv, adjektiv a sloves)
lemmata_most_freq = lemmata_freq.most_common(10)
print(lemmata_most_freq)

Nyní si tato data vizualizujeme.

In [ ]:
# kvůli horizontálnímu zobrazení prohodíme pořadí na našem listu
lemmata_mostfreq = lemmata_most_freq
lemmata_mostfreq.reverse()

# pro potřeby grafu přiřadíme hodnoty jednotlivým osám
height = [tup[1] for tup in lemmata_mostfreq]
bars = [tup[0] for tup in lemmata_mostfreq]
y_pos = np.arange(len(bars))

plt.barh(y_pos, height)
# graf si pojmenujeme a osu také
plt.yticks(y_pos, bars)
plt.xlabel('Frekvence výskytů')
plt.title('Frekvence výskytů nejčastějších slov')
# graf si zobrazíme
plt.show()

Přehled nejfrekventovanějších slov jistě představuje cennou informaci o obsahu zkoumaného textu či souboru textů. Neříká však nic o tom, jakým způsobem jsou zde příslušná slova použita. K tomu potřebujeme zaprvé a především informaci o tom, která slova se spolu a jak často spoluvyskytují. Tuto informaci získáme tak, že zkonstruujeme tzv. **kookurenční matici**.

In [ ]:
vocabulary = [tup[0] for tup in lemmata_freq.most_common(100)]
vect = CountVectorizer(vocabulary=vocabulary, lowercase=False)
X = vect.fit_transform([" ".join(sent) for sent in lemmatized_sentences])
Xc = (X.T * X)  # This is the matrix manipulation step
cooccurrence_matrix_df = pd.DataFrame(Xc.todense(), index=vocabulary, columns=vocabulary)
cooccurrence_matrix_df.head()

In [ ]:
kontrola_pruchodu(ntb="nlp", arg1=vocabulary[:10])

Pokud jsme se dostali až jsem, hlavní část našeho úkolu byla splněna. Máme-li však čas a chuť, můžeme pokračovat dále.

> **Zde končí povinná část cvičení.**

## Rozšiřující analýza: Analýza všech děl z Archivu Jana Patočky

Vraťme se nyní k tabulce všech děl v příslušném archivu:

In [ ]:
patocka_all_df.head(5)

Nyní můžeme veškerá textová data ve sloupci `rawtext` emmatizovat pomocí funkce níže. Tato procedura může být v případě větších korpusů relativně výpočetně náročná, proto ji zde budeme aplikovat jen obezřetně.

Musíme počítat s výpočtem trvacjícím několika minut. V případě časové tísně tento krok přeskočíme a posuneme se k buňce níže, kde se rovnou načtou již předzpracovaná data.

In [ ]:
def get_lemmatized_sents(rawtext):
  try:
    doc = czech_pipeline(rawtext)
    lemmatized_sentences = []
    for sent in doc.sentences:
        sentence_lemmata = []
        for token in sent.words:
            if token.upos in ["PROPN", "NOUN", "VERB", "ADJ"]:
                sentence_lemmata.append(token.lemma)
        lemmatized_sentences.append(sentence_lemmata)
    return lemmatized_sentences
  except:
    return []

In [ ]:
patocka_all_df["lemmatized_sents"] = patocka_all_df["rawtext"].apply(get_lemmatized_sents)

In [5]:
# v případě přeskočení předchozí buňky je potřeba v této buňce odmazat hashtag (#) na začátku následující řádky:
# patocka_all_df = pd.read_json("https://raw.githubusercontent.com/CCS-ZCU/pribehy-dat/master/data/patocka_all_df.json")
patocka_all_df.head(5)

/tmp/ipykernel_565/2849559750.py:2: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  patocka_all_df = pd.read_json("https://raw.githubusercontent.com/CCS-ZCU/pribehy-dat/master/data/patocka_all_df.json")
/tmp/ipykernel_565/2849559750.py:2: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  patocka_all_df = pd.read_json("https://raw.githubusercontent.com/CCS-ZCU/pribehy-dat/master/data/patocka_all_df.json")
/tmp/ipykernel_565/2849559750.py:2: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  patocka_all_df = pd.read_json("https://raw.githubusercontent.com/CCS-ZCU/pribehy-dat/master/data/patocka_all_df.json")

,url,title,date,rawtext,lemmatized_sents
0,https://archiv.janpatocka.cz/items/show/98,"Recenze na: J. Kratochvil, Meditace věků. Ději...",1932,Josef Kratochvil: Meditace věků. Dějinný vývoj...,"[[Josef, Kratochvil, meditace, věk], [dějinný,..."
1,https://archiv.janpatocka.cz/items/show/335,"Recenze na: H. Gouhier, La jeunesse d’Auguste ...",1936,None,[]
2,https://archiv.janpatocka.cz/items/show/66,"Recenze na: J. Benda, La fin de l’éternel",1929,"Julien Benda, La fin de 1’eternel, Paris, Gall...","[[Julien, Benda], [strana, cena, frs], [nový, ..."
3,https://archiv.janpatocka.cz/items/show/30,Gorgias\n,None,﻿Ještě ve stručnosti zopakuji hlavní body té K...,"[[stručnost, zopakovat, hlavní, bod, Kallikleů..."
4,https://archiv.janpatocka.cz/items/show/95,"Recenze na: G. Ipsen, Sprachphilosophie der Ge...",1932,"Philosophische Forschungsberichte, Junker und ...","[[Berlin], [Heft, Gunther, Ipsen, 8°, strana, ..."

In [6]:
patocka_all_df.shape

(363, 5)

In [7]:
# získaná data si vyexportujeme do samosatné proměnné v podobě listu lematizovaných vět a ten následně také do listu lematizovaných slov.
all_sents = [sent for doc in patocka_all_df["lemmatized_sents"] for sent in doc]
docs = [" ".join(sent) for sent in all_sents]
lemmata_flat = [t for s in all_sents for t in s]
# z listu slov spočítáme frekvence
lemmata_freqs = nltk.FreqDist(lemmata_flat).most_common()
vocabulary = [tup[0] for tup in lemmata_freqs][:500]
lemmata_freqs[:10]

[('mít', 3801),
 ('život', 2831),
 ('svět', 2785),
 ('moci', 2634),
 ('smysl', 2580),
 ('věc', 2569),
 ('člověk', 2182),
 ('způsob', 1713),
 ('bytí', 1614),
 ('muset', 1502)]

In [8]:
# z těchto dat opět vytvoříme matici spoluvýskytů
vect = CountVectorizer(vocabulary=vocabulary, lowercase=False)
X = vect.fit_transform(docs)
Xc = (X.T * X)  # This is the matrix manipulation step
cooccurrence_matrix_df = pd.DataFrame(Xc.todense(), index=vocabulary, columns=vocabulary)
cooccurrence_matrix_df.head()

,mít,život,svět,moci,smysl,věc,člověk,způsob,bytí,muset,...,ideál,začínat,rok,vnímání,jednoduchý,centrum,učinit,zjevovat,dojem,přel
mít,5015,424,422,539,762,512,444,240,272,439,...,19,22,5,15,17,15,16,26,43,4
život,424,4589,413,298,425,233,551,333,169,174,...,21,12,1,9,18,20,9,5,12,8
svět,422,413,4361,316,366,335,410,211,284,160,...,5,10,7,9,10,12,15,40,12,6
moci,539,298,316,3392,480,348,314,251,254,287,...,14,7,7,8,17,6,10,21,21,5
smysl,762,425,366,480,3614,294,293,190,294,196,...,13,9,5,6,15,12,14,35,8,10

In [9]:
# pro efektivitu analýz zredukujeme dimenzionalitu
svd = TruncatedSVD(n_components=100)  # choose the number of components
X_reduced = svd.fit_transform(Xc)

In [10]:
embeddings_df = pd.DataFrame(X_reduced, index=vocabulary)

def most_similar(word, n=10):
    if word not in embeddings_df.index:
        print(f"Slovo '{word}' není ve slovníku.")
        return pd.DataFrame()

    word_vector = embeddings_df.loc[[word]]
    similarities = cosine_similarity(word_vector, embeddings_df)[0]

    result = pd.DataFrame({
        "word": embeddings_df.index,
        "similarity": similarities
    })

    result = result[result["word"] != word]
    return result.sort_values("similarity", ascending=False).head(n)

most_similar("svět")

             word  similarity
155     přirozený    0.897479
420        naivní    0.775278
467     technický    0.745130
265        božský    0.709536
464         okolí    0.666563
378      horizont    0.664741
396   křesťanství    0.661613
279          víra    0.634888
479     radikální    0.634267
418  pochopitelný    0.634215